"""
Enrichment Models

Data provenance, quality tracking, and enrichment metadata.
"""

from enum import Enum
from datetime import datetime
from pydantic import BaseModel, Field
from typing import Optional


class DataSource(str, Enum):
    """Source of diagnostic data"""
    OEM = "oem"  # Official manufacturer data
    MANUAL = "manual"  # Manually curated by expert
    AI_GENERATED = "ai_generated"  # Generated by AI
    COMMUNITY = "community"  # Community-contributed
    UNKNOWN = "unknown"  # Source not tracked


class EnrichmentStatus(str, Enum):
    """Completeness status of diagnostic entry"""
    NOT_ENRICHED = "not_enriched"  # Only basic fields (code, description)
    PARTIAL = "partial"  # Some enrichment fields present
    AI_GENERATED = "ai_generated"  # Fully enriched by AI
    AI_ENRICHED = "ai_enriched"  # AI-enhanced version of existing data (alias for ai_generated)
    REVIEWED = "reviewed"  # AI-generated + human review
    OEM_VERIFIED = "oem_verified"  # Verified against OEM documentation


class FieldMetadata(BaseModel):
    """
    Metadata for a single diagnostic field.

    Tracks source and when/how the data was generated.
    Confidence is derived from source, not stored as arbitrary float.
    """
    source: DataSource = DataSource.UNKNOWN
    generated_at: Optional[datetime] = None
    ai_model: Optional[str] = None  # e.g., "claude-sonnet-4"
    prompt_version: Optional[str] = None  # e.g., "v6"

    def get_confidence(self) -> float:
        """
        Confidence derived from source (not arbitrary).

        Returns:
            Confidence score 0-1 based on source
        """
        confidence_map = {
            DataSource.OEM: 0.98,
            DataSource.MANUAL: 0.95,
            DataSource.AI_GENERATED: 0.80,
            DataSource.COMMUNITY: 0.70,
            DataSource.UNKNOWN: 0.50
        }
        return confidence_map.get(self.source, 0.50)


class EnrichmentMetadata(BaseModel):
    """
    Complete enrichment metadata for a diagnostic code.

    Tracks provenance and quality for each enriched field.
    """
    # Field-level metadata
    symptoms_meta: Optional[FieldMetadata] = None
    causes_meta: Optional[FieldMetadata] = None
    checks_meta: Optional[FieldMetadata] = None
    severity_meta: Optional[FieldMetadata] = None
    technician_tip_meta: Optional[FieldMetadata] = None
    pre_replacement_checks_meta: Optional[FieldMetadata] = None

    # Overall metadata
    enrichment_status: EnrichmentStatus = EnrichmentStatus.NOT_ENRICHED
    knowledge_score: float = Field(ge=0.0, le=100.0, default=0.0)  # 0-100
    last_enriched: Optional[datetime] = None
    enrichment_version: int = 1  # Increment when re-enriched


def calculate_knowledge_score(
    has_description: bool,
    has_symptoms: bool,
    has_causes: bool,
    has_checks: bool,
    has_severity: bool,
    has_severity_explanation: bool,
    has_technician_tip: bool,
    has_pre_replacement_checks: bool,
    has_system: bool
) -> float:
    """
    Calculate knowledge score (0-100) based on field completeness.

    Weights:
    - Description: 15% (required)
    - Symptoms: 10%
    - Causes: 15%
    - Checks: 15%
    - Severity: 10%
    - Severity Explanation: 5%
    - Technician Tip: 15%
    - Pre-replacement Checks: 10%
    - System: 5%

    Returns:
        Score from 0-100
    """
    weights = {
        'description': 15,
        'symptoms': 10,
        'causes': 15,
        'checks': 15,
        'severity': 10,
        'severity_explanation': 5,
        'technician_tip': 15,
        'pre_replacement_checks': 10,
        'system': 5
    }

    fields = {
        'description': has_description,
        'symptoms': has_symptoms,
        'causes': has_causes,
        'checks': has_checks,
        'severity': has_severity,
        'severity_explanation': has_severity_explanation,
        'technician_tip': has_technician_tip,
        'pre_replacement_checks': has_pre_replacement_checks,
        'system': has_system
    }

    score = sum(weights[field] for field, present in fields.items() if present)
    return float(score)


def determine_enrichment_status(knowledge_score: float, has_manual_review: bool, has_oem_data: bool) -> EnrichmentStatus:
    """
    Determine enrichment status based on score and provenance.

    Args:
        knowledge_score: Completeness score (0-100)
        has_manual_review: Whether data has been manually reviewed
        has_oem_data: Whether data comes from OEM source

    Returns:
        EnrichmentStatus
    """
    if has_oem_data:
        return EnrichmentStatus.OEM_VERIFIED
    elif has_manual_review and knowledge_score >= 80:
        return EnrichmentStatus.REVIEWED
    elif knowledge_score >= 80:
        return EnrichmentStatus.AI_GENERATED
    elif knowledge_score >= 40:
        return EnrichmentStatus.PARTIAL
    else:
        return EnrichmentStatus.NOT_ENRICHED
