"""
Insert validated system diagrams into database.

Reads import_results.json (generated by import_from_spreadsheet.py)
and inserts validated records into the system_diagrams table.
"""
import os
import sys
import json
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db.client import get_supabase_client
from app.repositories.system_diagram_repository import SystemDiagramRepository
from app.core.logging import logger


RESULTS_FILE = "import_results.json"


def load_validation_results():
    """Load the validation results from import_from_spreadsheet.py"""
    if not os.path.exists(RESULTS_FILE):
        print(f"[X] ERROR: {RESULTS_FILE} not found.")
        print(f"   Run import_from_spreadsheet.py first to validate images.")
        sys.exit(1)

    with open(RESULTS_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def check_existing_systems(repo: SystemDiagramRepository, systems: list[str]):
    """
    Check which systems already exist in database.

    Returns:
        dict: {system_name: SystemDiagram or None}
    """
    print("\n[SEARCH] Checking for existing records...")
    existing = {}

    for system in systems:
        diagram = repo.get_by_system(system)
        existing[system] = diagram
        if diagram:
            print(f"   [WARN] '{system}' already exists (ID: {diagram.id})")

    return existing


def insert_system_diagrams(
    repo: SystemDiagramRepository,
    validated_items: list[dict],
    mode: str = 'skip'
):
    """
    Insert validated system diagrams into database.

    Args:
        repo: SystemDiagramRepository instance
        validated_items: List of validated items from import_results.json
        mode: 'skip' (skip existing), 'update' (overwrite existing), or 'insert-only' (error on conflict)

    Returns:
        dict with keys: inserted, updated, skipped, failed
    """
    results = {
        'inserted': [],
        'updated': [],
        'skipped': [],
        'failed': []
    }

    print(f"\n[IN] Inserting {len(validated_items)} system diagrams (mode: {mode})...\n")

    for idx, item in enumerate(validated_items, start=1):
        system = item['system']
        print(f"{idx}. {system}")

        try:
            if mode == 'update':
                # Upsert: insert or update if exists
                diagram = repo.upsert(
                    system=system,
                    image_url=item['image_url'],
                    source=item['source'],
                    license=item['license'],
                    attribution_text=item.get('attribution_text'),
                    caption=item.get('caption')
                )

                if diagram:
                    # Check if it was insert or update
                    existing = repo.get_by_system(system)
                    if existing:
                        results['updated'].append(system)
                        print(f"   [OK] Updated")
                    else:
                        results['inserted'].append(system)
                        print(f"   [OK] Inserted")
                else:
                    results['failed'].append({'system': system, 'reason': 'Upsert returned None'})
                    print(f"   [X] Failed")

            elif mode == 'skip':
                # Check if exists first
                existing = repo.get_by_system(system)
                if existing:
                    results['skipped'].append(system)
                    print(f"   [>>] Skipped (already exists)")
                else:
                    # Insert new
                    diagram = repo.insert(
                        system=system,
                        image_url=item['image_url'],
                        source=item['source'],
                        license=item['license'],
                        attribution_text=item.get('attribution_text'),
                        caption=item.get('caption')
                    )

                    if diagram:
                        results['inserted'].append(system)
                        print(f"   [OK] Inserted")
                    else:
                        results['failed'].append({'system': system, 'reason': 'Insert returned None'})
                        print(f"   [X] Failed")

            else:  # insert-only
                # Try insert, fail if exists
                diagram = repo.insert(
                    system=system,
                    image_url=item['image_url'],
                    source=item['source'],
                    license=item['license'],
                    attribution_text=item.get('attribution_text'),
                    caption=item.get('caption')
                )

                if diagram:
                    results['inserted'].append(system)
                    print(f"   [OK] Inserted")
                else:
                    results['failed'].append({'system': system, 'reason': 'Insert failed (may already exist)'})
                    print(f"   [X] Failed")

        except Exception as e:
            results['failed'].append({'system': system, 'reason': str(e)})
            print(f"   [X] Error: {e}")

    return results


def verify_imports(repo: SystemDiagramRepository, systems: list[str]):
    """
    Verify that all systems can be retrieved from database.

    Returns:
        dict with keys: verified (list), missing (list)
    """
    print("\n[SEARCH] Verifying imports...")
    verified = []
    missing = []

    for system in systems:
        diagram = repo.get_by_system(system)
        if diagram:
            verified.append(system)
            print(f"   [OK] {system}")
        else:
            missing.append(system)
            print(f"   [X] {system} - NOT FOUND")

    return {
        'verified': verified,
        'missing': missing
    }


def print_final_report(insert_results: dict, verify_results: dict):
    """Print final import report"""
    print("\n" + "="*80)
    print("[CHART] IMPORT COMPLETE")
    print("="*80)

    print(f"\n[OK] Inserted: {len(insert_results['inserted'])}")
    if insert_results['inserted']:
        for system in insert_results['inserted']:
            print(f"   * {system}")

    print(f"\n[LOOP] Updated: {len(insert_results['updated'])}")
    if insert_results['updated']:
        for system in insert_results['updated']:
            print(f"   * {system}")

    print(f"\n[>>] Skipped: {len(insert_results['skipped'])}")
    if insert_results['skipped']:
        for system in insert_results['skipped']:
            print(f"   * {system}")

    print(f"\n[X] Failed: {len(insert_results['failed'])}")
    if insert_results['failed']:
        for item in insert_results['failed']:
            print(f"   * {item['system']}: {item['reason']}")

    print(f"\n[SEARCH] Verification:")
    print(f"   [OK] Verified in database: {len(verify_results['verified'])}")
    print(f"   [X] Missing from database: {len(verify_results['missing'])}")

    print("\n" + "="*80)


def main():
    """Main insertion workflow"""
    print("="*80)
    print("[SAVE] SYSTEM DIAGRAM DATABASE INSERTION")
    print("="*80)

    try:
        # Load validation results
        results = load_validation_results()
        validated = results['validated']

        if not validated:
            print("\n[WARN] No validated items to insert.")
            return

        print(f"\n[CLIP] Found {len(validated)} validated items")

        # Connect to database
        print("\n[PLUG] Connecting to database...")
        supabase = get_supabase_client()
        repo = SystemDiagramRepository(supabase)

        # Check for existing systems
        systems = [item['system'] for item in validated]
        existing = check_existing_systems(repo, systems)
        num_existing = sum(1 for v in existing.values() if v is not None)

        # Determine mode
        if num_existing > 0:
            print(f"\n[WARN] {num_existing} system(s) already exist in database.")
            print("\nChoose action:")
            print("  1. Skip existing (only insert new)")
            print("  2. Update existing (overwrite with new data)")
            print("  3. Cancel")

            choice = input("\nEnter choice (1-3): ").strip()

            if choice == '1':
                mode = 'skip'
            elif choice == '2':
                mode = 'update'
            else:
                print("\n[X] Cancelled.")
                return
        else:
            mode = 'skip'  # No conflicts, doesn't matter

        # Insert
        insert_results = insert_system_diagrams(repo, validated, mode)

        # Verify
        systems_to_verify = (
            insert_results['inserted'] +
            insert_results['updated']
        )
        verify_results = verify_imports(repo, systems_to_verify)

        # Final report
        print_final_report(insert_results, verify_results)

    except FileNotFoundError as e:
        print(f"\n[X] ERROR: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n[X] UNEXPECTED ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
